### ISSUE TITLE
send buttons/templates

### ISSUE THREAD

**Issue by ssteeltm** [asternic/wuzapi#10]
Hello, Sends a template message, that can contain quick reply buttons, url buttons and call buttons isnt working, gives me 404 error.
Saw that it was commented in last update, whatsmeow stopped working with templates?

**Comment by asternic** [comment]
Yes, last whatsmeow updates broke that feature. I did not have the time to see how to reimplement it.

**Comment by asternic** [comment]
Buttons sending was re-enabled on commit 8a5d114 (but not templates).
