### ISSUE TITLE
Client outdated (405) connect failure

### ISSUE THREAD

**Issue by punyahenry** [asternic/wuzapi#14]
2023-06-15T10:24:40+07:00 INF Already logged in, just connect host=0.0.0.0 role=wuzapi
10:24:40.510 [Client/Socket DEBUG] Dialing wss://web.whatsapp.com/ws/chat
10:24:48.665 [Client/Socket DEBUG] Frame websocket read pump starting 0xc000192420
10:24:54.332 [Client/Recv DEBUG] <failure location="atn" reason="405"/>
10:24:54.332 [Client ERROR] Client outdated (405) connect failure
2023-06-15T10:24:54+07:00 WRN Unhandled event event=&{} host=0.0.0.0 role=wuzapi
10:24:54.429 [Client/Socket ERROR] Error reading from websocket: websocket: close 1006 (abnormal closure): unexpected EOF
10:24:54.430 [Client/Socket DEBUG] Frame websocket read pump exiting 0xc000192420

any update for this case?

**Comment by asternic** [comment]
Commit c5c2bca updates to latest whatsmeow module and should fix that error.
