### ISSUE TITLE
cant run web after update

### ISSUE THREAD

**Issue by ssteeltm** [asternic/wuzapi#15]
Hello, thank you for wuzapi!
After git pull update I cant login in web:
![image](https://github.com/asternic/wuzapi/assets/17302120/429d314f-e5bf-4583-a4b4-e0824960b7fd)

**Comment by ssteeltm** [comment]
As I see it's not creating the databases main and users

**Comment by ssteeltm** [comment]
If I swtich to my old main.go it creates but still 404 on web

**Comment by asternic** [comment]
How do you start wuzapi? What command are you using? A few commits past I modified the code to look for the binary path and use that as a base for finding both static and dbdata directories. Do you have those directories on the same folder of the wuzapi binary?

**Comment by ssteeltm** [comment]
For now testing and debugging, I run it with "go run ."

I made it work, found this change on path and changed back to the old code

**Comment by asternic** [comment]
With go run binary will be put in some /tmp directory and thus the static and dbdata directories won't be found when using filepath. I do not consider this to be a bug, you should build and run directly from there. Thanks!
