### ISSUE TITLE
failed on go run main.go

### ISSUE THREAD

**Issue by Rutik7066** [asternic/wuzapi#17]
# command-line-arguments
.\main.go:99:4: s.routes undefined (type *server has no field or method routes)
.\main.go:101:4: s.connectOnStartup undefined (type *server has no field or method connectOnStartup)

**Comment by ssteeltm** [comment]
You should "go run ." or build it.
With last change of dbdata path, "go run ." wont work anymore, so you should "go build ." and then use it.

**Comment by rutikthakre** [comment]
Thank you so much it is working now.
I need guidance on one more thing i am unable to send text message. I mean don't know where to specify token or username for wuzapi app to understand which user is sending message.

**Comment by asternic** [comment]
Set the token either as an url parameter or as a request header, example using curl and token as request header:

```
curl -X POST "http://wuzapi.server:8080/chat/send/text" -H "accept: application/json" -H "token: 1231231234" -H "Content-Type: application/json" -d "{\"Phone\":\"13005593934\",\"Body\":\"How you doin\",\"Id\":\"ABCDABCD\"}"
```
