### ISSUE TITLE
History Sync Not run on linux

### ISSUE THREAD

**Issue by kangzul** [asternic/wuzapi#18]
hello asternic, thanks for sharing this project. i have some problem when i use this project on linux server, event historySync not trigger after scanned QR. but this event work normally on local machine (windows).
this some information maybe you need it.

Server
- Ubuntu 22 LTS
- nginx
- no golang installed
- binary placed in ~/wuzapi/wuzapi
- use service from example service

Local Machine
- Windows 11 (22H2)
- installed golang (for build this project)
- run binary from project folder

the indication this not trigger, folder files/user_xxx not created after scanned QR, but this running well on local.
thanks.

**Comment by asternic** [comment]
Thanks, should be fixed on commit 12c9223e5bfd05b555ac13d1179d74a257a74a33
