### ISSUE TITLE
No está funcionando el Dockerfile (12/04/2024)

### ISSUE THREAD

**Issue by ruben18salazar3** [asternic/wuzapi#32]
Hola, en primer lugar quería agradecer por la creación de este proyecto, está muy interesante, me ha gustado mucho.

Además pasaba a reportar un error que me encontré el día de hoy (12/04/2024). No consigo crear la imágen docker ya que me da un error en durante el proceso:

  => ERROR [build 5/5] RUN go build -o server . 

Adjunto una imágen en donde se muestra el error completo:

![image](https://github.com/asternic/wuzapi/assets/86245508/ff474fcb-6294-492b-9d92-a17fa6222065)

Muchas gracias nuevamente.

**Comment by asternic** [comment]
Prueba modificar el Dockerfile y añadir antes de

RUN go build -o server .

la línea que te pide:

RUN go mod tidy

Fijate si asi le gusta y me comentas..

**Comment by ssteeltm** [comment]
I can confirm, that putting "RUN go mod tidy"  solved this issue
