### ISSUE TITLE
cant list users in admin endpoint

### ISSUE THREAD

**Issue by ssteeltm** [asternic/wuzapi#33]
Hello, I'm testing the new admin endpoint, and came to this:

![image](https://github.com/asternic/wuzapi/assets/17302120/818b0698-fb7d-4b7f-9ecc-eeabcec85893)

**Comment by ssteeltm** [comment]
solved and working after I made this comment on handlers:

![image](https://github.com/asternic/wuzapi/assets/17302120/0e086b8e-9407-4583-b868-d9e4714c60ce)

**Comment by HunterXProgrammer** [comment]
I think it's better to not comment out the error handling.

The probelm is during database table creation -

https://github.com/asternic/wuzapi/blob/b3cbcb7f99b1639abf8e8ad7c156ad6d74e10244/main.go#L88

You need to change `connected INTEGER,` to `connected INTEGER default 0,`.


Delete the `dbdata` folder and restart it.
