### ISSUE TITLE
BUG: Message_id from sent a message is different to events.Receipt 

### ISSUE THREAD

**Issue by monyuan** [asternic/wuzapi#39]
<img width="1288" alt="image" src="https://github.com/asternic/wuzapi/assets/56907515/7d085341-1d8b-44a4-a966-b0c4e8e25f8d">

https://github.com/tulir/whatsmeow/issues/343

**Comment by monyuan** [comment]
`	resp, err = clientPointer[userid].SendMessage(context.Background(), recipient, msg, whatsmeow.SendRequestExtra{ID: msgid})
		if err != nil {
			s.Respond(w, r, http.StatusInternalServerError, errors.New(fmt.Sprintf("Error sending message: %v", err)))
			return
		}`

**Comment by asternic** [comment]
Hi monyuan,

Not sure if I understand your proposed solution, adding a 4th parameter SEndRequestExtra? Can you send a pull request so I can check/test ?
