### ISSUE TITLE
QR code login not showing

### ISSUE THREAD

**Issue by funukonta** [asternic/wuzapi#40]
Today my wuzzapi client suddenly logged out, then i try to log in again, but i face this issue.

![error](https://github.com/asternic/wuzapi/assets/14922159/8abf4cfb-ab23-49c5-a0c6-b238a754be5a)

i try to hit `/session/qr`  and got this response

```
500 Error: Internal Server Error
{
  "code": 500,
  "error": "Not connected",
  "success": false
}
```

does anyone have any solution to this?

**Comment by sweetnight** [comment]
Same problem here. All of my device are also disconnected.

Seems WhatsApp updates it's connection system. Wuzapi must be updated too.

**Comment by GabrielKothe** [comment]
Same error/problem here.

**Comment by George-Seven** [comment]
WhatsApp is blacklisting data center/cloud IPs + IPs that don't match the geolocation of the phone numbers' country code. You can open a browser in the cloud server and even the official WhatsApp Web won't work.

You can use local device with normal IP address or you can try - https://github.com/tulir/whatsmeow/issues/584#issuecomment-2117092300

**Comment by asternic** [comment]
Did anyone try using /session/pairphone instead of /session/qr ? I suppose geolocation banning will affect both, but it would be nice if someone could try and confirm.

(/session/pairphone is a way to pair a device using a code instead of scanning a QR code, introduced some weeks ago).

**Comment by GabrielKothe** [comment]
I run wuzapi as an exe on each client's computer, each with its own ip and public ip. And it still gives an error.

**Comment by GabrielKothe** [comment]
@asternic  How can I update wuzapi with the new mdtest to test?

**Comment by asternic** [comment]
> @asternic How can I update wuzapi with the new mdtest to test?

git pull

That will get the changes from github on your local clone, then you can build again? Not sure if you mean that with your question. Wuzapi currently is not using the latest whatsmeow released yesterday that includes proxy support, in any case, if using a proxy works for some people, it means you still need a proxy machine somewhere. Waters are not clear enough yet to know why some people are having issues and some don't.

**Comment by GabrielKothe** [comment]
![image](https://github.com/asternic/wuzapi/assets/80685608/24a06490-dac0-4ed6-9539-411dc6798194)

@asternic  I updated wuzapi to the latest version and it worked. As I run wuzapi.exe on the client's own computer, there was no error.
