### ISSUE TITLE
failed to upgrade database: Binary was compiled with 'CGO_ENABLED=0'

### ISSUE THREAD

**Issue by badrullami** [asternic/wuzapi#42]
After build & run i got error :

panic: failed to upgrade database: Binary was compiled with 'CGO_ENABLED=0', go-sqlite3 requires cgo to work. This is a stub

goroutine 1 [running]:
main.main()

**Comment by asternic** [comment]
Enable CGO when building:

```CGO_ENABLED=1 go build```

**Comment by asternic** [comment]
Should work now with CGO_ENABLED=0
