### ISSUE TITLE
 Wuzapi has stopped working

### ISSUE THREAD

**Issue by GabrielKothe** [asternic/wuzapi#48]
wuzapi is not connected to the whatsapp session

/session/connect
'{"code":200,"data":{"details":"Connected!","events":"Message","jid":"","webhook":"http://localhost:8064/webhook"},"success":true}'#$A

/session/status
{"code":200,"data":{"Connected":false,"LoggedIn":false},"success":true}'

**Comment by DiazAdriel0** [comment]
I have the same problem

**Comment by asternic** [comment]
I have just updated wuzapi to the latest whatsmeow version. That will hopefully fix the connect issue to whatsapp.

Be carefull as there are some struct name changes:

url to URL
fileSha256 to fileSHA256
fileEncSha256 to fileEncSHA256
StanzaId to StanzaID

and probably others. If you parse structs in your code it will need to be updated.

**Comment by antoniocarlosdeoliveira** [comment]
Thank you very much for the wuzapi update, here I was able to run it again, everything was ok, working very well, thank you very much

**Comment by asternic** [comment]
Fixed with commit 99879886604546de9f3cbe771129fe67d10e9d15

**Comment by Luisdosveneno** [comment]
> Acabei de atualizar o wuzapi para a versão mais recente do whatsmeow. Espero que isso conserte o problema de conexão com o whatsapp.
> 
> Tenha cuidado, pois há algumas alterações no nome da estrutura:
> 
> url para URL fileSha256 para fileSHA256 fileEncSha256 para fileEncSHA256 StanzaId para StanzaID
> 
> e provavelmente outros. Se você analisar structs em seu código, ele precisará ser atualizado.

Mano me ajuda com esses arquivos, não consigo utilizar meu MDtest, me passa seu contato, pfvr preciso que ele funcione.
