### ISSUE TITLE
fail to downloadvideo

### ISSUE THREAD

**Issue by lordacer0** [asternic/wuzapi#49]
![image](https://github.com/user-attachments/assets/9dd50d01-513f-4d1f-8f01-00c0b4e8252c)

This error happens when trying to download the video of a message, and from what I see it is necessary to be able to forward the received video so that it is encoded in base64.

**Comment by asternic** [comment]
Hi, from the capture I notice that & characters are not properly escaped and are interpreted by the shell, breaking the parameter that is sent by curl. Please review your curl syntax, oh should be a parameter and not a new shell command.

**Comment by lordacer0** [comment]
Thanks for the response.  I was wrong in the query, downloading videos is not the problem, it is with images and documents. I close the issue as solved and open a new one.
