### ISSUE TITLE
Not able to connect to wuzapi after reboot

### ISSUE THREAD

**Issue by mjain234** [asternic/wuzapi#52]
How do I get to reconnect to wuzapi after Termux get crashed or say after reboot? Because whenever I am trying to connect after reboot, and give command ./wuzapi , though it gets connected but I am not able to receive messages thereafter.

What am I doing wrong here?

**Comment by mjain234** [comment]
While I am trying to connect to ./wuzapi , it still says " No session". See this [video](https://drive.google.com/file/d/1jr8gVKCpsH7wvlpYZBHXVwcH9eRTNusb/view), even though linked devices are connected

**Comment by ariefsn** [comment]
Hi, I am facing this issue today, too.
Can you check the log?
In my case when I check the log, I get the error that the client was outdated.
![Wuzapi  Client Outdated - No Session](https://github.com/user-attachments/assets/bc15a764-0414-468e-bc6e-97f654d9286e)
If this is the same, just upgrade the client. 😇

**Comment by mjain234** [comment]
How do I check the log?

**Comment by ariefsn** [comment]
Should be where you start the `wuzapi` app.

**Comment by mjain234** [comment]
> Hi, I am facing this issue today, too.
> Can you check the log?
> In my case when I check the log, I get the error that the client was outdated.
> ![Wuzapi  Client Outdated - No Session](https://github.com/user-attachments/assets/bc15a764-0414-468e-bc6e-97f654d9286e)
> If this is the same, just upgrade the client. 😇

Have you checked the video i provided? It doesn't show up any logs or any whatsapp received.

**Comment by asternic** [comment]
For anyone having connection issues, please checkout and upgrade, I updated wuzapi about a week ago.

**Comment by mjain234** [comment]
I am just asking a simple question, how would I reconnect after rebooting my phone to wuzapi?

**Comment by asternic** [comment]
If you open a session with wuzapi and pair via code or QR, you have the session created in wuzapi. If you restart wuzapi for any reason it will restore that session (no need to pair again). If you kick/close the session from your phone, you will need to login/scan qr/code again as you do with whatsapp web or similar. 

You must check the logs if something does not work, as your problem might be something totally different than you think it is, perhpas termux crashing is not an issue at all, but having an outdated client is.
