### ISSUE TITLE
Docker Image

### ISSUE THREAD

**Issue by ArchonMegalon** [asternic/wuzapi#55]
Since you already meantion Docker:

Could you provide a "official" Docker image? There are some on DockerHub - but no description/documentation or really anything that suggests, they are save to use.

Maybe even a compose file for portainer?

**Comment by lordacer0** [comment]
Good afternoon, you just have to create the image with the Dockerfile file that is in the repository. Clone the repository, and then with the command "docker build -t wuzapi ." (wuzapi or whatever name you want the image to have) you generate the image, it does not weigh more than 50mb. Greetings.
