### ISSUE TITLE
[Send Image Message] thumbnail preview

### ISSUE THREAD

**Issue by hernanbozzano** [asternic/wuzapi#56]
As title, is there any way to implement this feature? when you send an image through whastapp it really looks awful without the blurry preview before downloading it

**Comment by asternic** [comment]
Not really sure about this, but I modified the image sending to set the JPEGThumbnail in commit 4c2ec6e885258fe0bac77076ec0ad701126854c8

You might want to try it out and see if its what you are looking for/works as expected.

**Comment by hernanbozzano** [comment]
yes! it worked like a charm! you're awesome!

as far as i can see you are Argentinian like me, muchas gracias Nico!
