### ISSUE TITLE
Wrong http request method for Group Link / Info?

### ISSUE THREAD

**Issue by PoroFever** [asternic/wuzapi#57]
in API swagger it shows both group/invitelink and group/info http requests methods as GET
yet it requires a body (to send groupJID).

when I use the example (changing only the groupJID), I get:

'TypeError: Failed to execute 'fetch' on 'Window': Request with GET/HEAD method cannot have body.'

I guess wrong request method?

**Comment by asternic** [comment]
Fixed on 1c39177bab737479a7870f801279ad4cb98a27e5 using request parameters instead.
