### ISSUE TITLE
Send Image Message Error

### ISSUE THREAD

**Issue by PoroFever** [asternic/wuzapi#58]
Send Image works when posting Phone, Image, and with/without caption.
But when I try to reply with an Image (adding Context Info (StanzaId, Participant)), it shows

Code: Undocumented    TypeError: Failed to Fetch 

PD: sos un capísimo, Nico

**Comment by GabrielKothe** [comment]
Same error


Send imagem with caption dont work

**Comment by GabrielKothe** [comment]
Sending a png image stopped working, wuzapi is only accepting base64 jpeg

{
  "Phone": "556xxxxxxx",
   "Image": "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAASwAAAA4CAYAAABHTcVMAAAAAXNSR0IArs4c6QAADYNJREFUeF7tXUuMZkUVrn/s6RgMb2Y0Rp7ddCcsTHTnQhS3ho0JLHluYMMKYiBRNC5wS9y4EdHEhRp3rn3EhcYFC9AQ6J4ZCLMjvBNg7KavnJ4+TE1xnnXr/vf+t89NJv/M/PfWOeerU1+dOnVu/Yv0+euWlNL9KSX4/O7RJ3HbZP7rtZQS/PlbSuk3R3+fjHKhSCAQCLRDYFE09fSn//5Ju+ZHaenBT0n2+VEkh9BAIBAYFIGcsP56FFENKnBJjQNhAXHFFQgEAjNCAAlrDpFV2S0QKf50Rn0VpgQCxx4BICzIVZ2bKRK3Rk5rpj0bZh1LBICw5hhdYWdGPutYunUYPVcEgLDmlLsq+2nMXBZErtQFO5pxBQKBQAUCQFhdxXOr8giUOtw1krIUrmMS6EgwhNhAoB0CcycsQKos3WiHntxSENaykA45s0Ngb3vjR+kgfS8t0nuLxeJ3a6/s/hEH85wjrCCs2blyGDR3BPa3Np7vLhavf3Ytuu7utZ2zf44Ia7jejwhrOGyj5Zki8N877ljf2r9woTSv67rn1nfOPhyENVzHB2ENh220PFMEupRO7G9tfJxSOpmb2HXpl+s7Zx4Nwhqu44OwhsM2Wp4xAnvbG8+mLj12uYkHd5589dw/grCG6/ggrOGwXZWWobQF6hzhE2oCo6TF2HP/277toRPd4ttdt3i369Lv13d3/xVJdyN4lbcFYVUCN5PH4KQTqHHEK966aNCxEWE1AJFpIghrOGyn3jL19shY5TVTx8ql39iEBYWUVJj8AHUO180n1w6Ne31v32PkWI4ShOXppXncC0u/XxOnnkTBcKP+HZuwuDD5steF7rvqyvSrr5w+NPnvH36Ufvb2O4efxqsVYQGJfueISMEx8dDAQ7WO/p2TbyvCwkMUS9l4cCHKBj1a5kgoe1EGHpSYy6MOe8wxyruLOxjSc44Z6FdenLzyPnz25qw/sU8R19ePDoW0YlouAXOZeLik5rKa/aB3qXPe7yCH8kVNbu33iCP4JlyAAeIFugCG1j5BHa5MKd3DKPTc5AnrG19cf+vfN914fWnAqd1z77x7cHCtAek+hAUdAOE9fFouSKxCR0En9SUscAZM2Fpkg1w4Tgc+ay+vzNxe6p1U7ogf6l7ADCYwy8WdMKIdKeS1D3QBEgGClnBtcYAAZz/4HhRRek//zfvGgqnnHi+OHt8EwnqfUAYq3e+dPGE9cs3VO784fcPtpQF3vnH+hX9+dOGbBpRrCav2pXDoHHAW6sgey9LAS5IlBB7nwGdBJixluBe2JZgle7nTMlqQOehbXvDeKEUsUvRjcKHDWygy5JaA1jbz+yjf6EuE2DfWKFHTuy+OFn1Wm7CeOXXDi49fe/XXl0hYLZ2wVFsjrL4OkcvjBm+pU99BgVEItUSjlvy10VGuN6czNTm1xDQnrZbtUoRYO2GW/QtkBb7Ql7Ra2avps9qE9f0vXXH+2dOnvoYJd+gNSLpvnoPlsenyRlitHIVSTiIsi0NgPgAGPUZDUlSkbaW3ICupEyjsgdg80RHVvnVJqR1OSW36QD9IKQDElLPD5JTETXk0qvkg5rqQhLQfjNGWyprOFlsx9wdtab4p6bPahAXWQ9L9x9dfl4C0fvv+B4d/Bkq6awMYQlpMJsIndAwmwy05Bo6wpIEFjgC5KS4hK+UTpNlMc0J4FmTmyWccyJa8HpeT8URH3ECilpTUUUKcLO3YISnKxj6k+psiYm/CXZq4YKBLvwwF9pI77Ef5wdooC9Ib1MSo+aakD7cCWH3C0uhf+d4aYfUhDVQBt7S5qIcjrNqBhXJBHszKlFwqj6RFHpaTWrW8F2erNTriutWzpIT+sC5VKXn5QM13u6gfOOH0smCZy+bIoe8S3/p8iQNHoNZNEs63uSgrCMtIeFJ05elsqR1qEHOObnUINI9zLEomN5C9MiVbOYekoiOPXA9hcUsrK4ngNr0lMuEiVqus3E0xeoMSBtTB8itQcC9E/NRP9dXoATphVJ2X1eCrRpYdac4vuSg3CMtIWNzMVrP+59ry7ARh+G9U//A2ameyJAMpuvIQM+rliQg8ZMPZzZEkpTtHzNA2Lu9b1S1xeml5RE//5vfmNVCWdEQtYXn08+pErX6CsIyIcwcZWpeUpTNR+QwPYRnVNt2WDxpviK4J4AiLwm1IwuLkcUtlyq4+JMaRY43/UMsyzJdayImyrWYy0voei4trdRqdsKjdC9zRovIrpkp3DbUGOaxWy7Ka5Zm2I9TT/MPH89mVG1i1Du3JSXmiI85ujzxoQ9tIkfC11A1JkaaW3Nf6VsuJas/n37cgTmgPSAoLWT3yqXtHISzcBdFeK8Ct17x6eyqE5V1nax3FESAVYS2DsHIy4uTVODRnJzdQl7lDmPeRtkGg9adlOdW3GDbXoZZkcee6DA48OUIOC2nnVMMP5FMBy1IJq6aiGg3DmYMraGs5iC0DUcrrWJ6nQvj8aBH8fizCym3wLOE0R/Qu8bzRUSnfK4/qF5wwuZ1czmYpl8lNeBaiK+VZfR8DBMjB4etg0Bb1fN9IT9qFLvXH2ra8HMYzUQ2Sw+oLABgJncztMlg7TRtQ8L2VcLiBXJM05TrIs2PXojoZ8cl3uThsa+zk2uIGN4WxZ/bncK0hBtxRy/MvGolxGLUohtWWr+A7JTm1JnTPMjyfhDW9PPnh5oSlvV5iIRHtnjEIyzv4pNCZ2q2D+ynsOGev2Z0EGTDopG14LofllSf1EZcP61vS4NmR1HyM+h7ISyqK5exqtUPI4YMvMms2terbXE7f/K539dKUsLyRlTZ4ahhd67Tye2uEJVV+ewazNJA5suciD2+UhbKl3S7JTkuUZcllcJj3iWIlXEt5mC/Fo1gwmrfUMoH/cHpykVyLzYS+y12phKN2QwVXQlR6wzImNF8ZPIelOTQ4BnUUBi79rOdajxFhSY6K0RG8IsNFL9rszEVY0lIAZFlnVw6zcpLR8hFAqpSdUlFiPklISzxOR+kVIs3pKXlewiknOS8Bed9UoCbyPoWn2nhhJ+29zc1vLRYHt3xhbfHS4uUz/yGigdoVgGU8DEpYEqNqTpXjwA2I/B6tAzxRljXC0nIIKBPJF3dkcBbS8h8SYWkkUkZMuPTD2hzq9RPUl5pkrLtQ3K6ThL+UMtDk5glbjI4k2zhMtbcNpImHe1YiYkkevtIDn/mL1WXUI70CQ0XaWAOl4cPqvbe18aeU0g8udWb3zMlXzz5VdK70biPqVb6EbS17GJSwpOjKSzBaOOltTxpAHsKykpaHMEuy5pYl3kPRLDpIOLfEONdFm9g8hZy1NmoTALSbny6QTwCcTImIpTwN1x6FExcZor7YlmVyxHtJvfe3N+/puu4PpXJ7n6Sbrjhz5o3i/yW9UDePTtj8YIRVO7tIDresweQlLNBZygdYBlE+41gJC+5rSVrapOCJiimbgXhrjonRoiwJX6qeRzq0r/ZQwlIHS+7W6zPUmOqDDZY2lBEX6Qd727f9MHWLn38e7Iu//1f8fx+9MMKkIsHBCEuaXWpnaskJatuknL2GsDDS4o7qsBAxZYNlh7UvkYBuniSrt6gSbIAjTuCikrEWvL0DAHN51A6eJM8SaWkTkKXPMEKjfoBCap/qJy820D6SEuVzpC/sbW/clbr0l0K5D9Y+vPDlxfnz1A8m1OiFtZoeX2mySyjN1lyNheYI8D3nbFMgLNQfOspCXDiQMcdFzbhW5wfZmLSEQWcJt7FOR3vjgOsXsBFPB8hl4gxZ1tpQDuypqbISZe57pV9Y5XmxBIxqz0S3DGzQG/2F2sSxYlPmg6lxwyfctzafSql7IqV0TdelnROpe3Jt5yzktbjLkkiHZ8uxwOXBBo2wqERlzdo9B4M6BgO+txCEhRAlUrQ+j/flR37g/0m/rMKRjOWoklK3Uja0DQQCF+Ziatr1YpDfT01U2jKUkoe7jxiloF159TY+R2HqtZvCEtrAX3gpc1s1GKGeaBvq6P0VmfJoF9STwgbxK/VV8ek2N08tdnffdBia65WPBfh7X90gwvoqo8srwHDWCAkMx19lQRAss4kDh0FutSxRBhG8Ao2i41nONcrN4SaqmorzFYApVJwKAh7CynVGB0eHn4o9lB5BWBdRwWJKOIgtfx1FqoGi8ORybNbl2ZR9JXSbOAK1hDVxsy5TLwjrEhx9DymUNgRqloOr5Eeh6wQQCMKaQCcsUQVpCS+dvqEVKUZ0tcROPM6igrCOX+9rRYCYOMVlpLZDiSUH3jzY8UM+LO6NQBBWbwhXrgHrlrnVME/Nl7XNuC8QIBEIwjqejtGCtPoc4Hg8UQ+reyMQhNUbwpVtAJZ6WDmuLftyI8uiwJUFIBRfPQSAsCw5jdWz7KLGkQy29Rwm1fMKdzwCBXNT+HNYkauyYRp3DYAAEJb3pc0B1BisSc+rMIMpEQ0HAoFAGwSAsFahWr3W2qgNqkUungsEJogAEFaLN9onaFosB6fYKaFTINAHAawCn2OUFdFVH8+IZwOBCSKQv7bS8kiXsU21HLg2to4hPxAIBJwIlO/ZWc9+copZ6u1RyLhUuENYILA8BKgXgyGnlf/yjadGZ3maX5LEHTA3hi4hMxAIBAZE4P8s6yV1PgltxwAAAABJRU5ErkJggg==",
  "Caption": "Image Description"
}


Response


{
    "code": 500,
    "error": "Could not decode image for thumbnail preparation: invalid JPEG format: missing SOI marker",
    "success": false
}

**Comment by asternic** [comment]
Fixed png/gif I think, but not sure about replying to image messages, I think its not a related issue. Can you test it @PoroFever ?

**Comment by PoroFever** [comment]
@asternic  
Still same error.
When I send Image Message with Phone, Image and Caption, it works... but as when I add ContextInfo (StanzaId and Participant) it gives me 
![image](https://github.com/user-attachments/assets/24ac2f4d-6a47-4cb7-90c5-8cfc8f0fc455)

Note: I don't use ID because... I don't know what to fill it with, but it works without it, at least in a "normal" image message.

**Comment by PoroFever** [comment]
About @GabrielKothe 's reported issue, it seems to be working now...  (I used his example but with my phone number and it worked)
